[package]
name = "luajit"
version = "0.1.12"
edition = "2024"

[dependencies]
mlua = { version = "0.11.4", features = ["luajit", "vendored", "serde"] }
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"]}
zip = "0.6"
walkdir = "2"
sys-info = "0.9.1"
open = "3"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
dirs-next = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
dotenv = "0.15"
serde_yaml = "0.9"
ini = "1.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "wincon"] }
windows = { version = "0.62.1", features = ["Win32_System_Console"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
