[package]
name = "luajit"
version = "0.1.3"
edition = "2024"

[dependencies]
mlua = { version = "0.11", features = ["luajit", "vendored"] }
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"]}
zip = "0.6"
walkdir = "2"
