# To start the site
# mkdocs serve --dev-addr 0.0.0.0:9000
site_name: Luajit Rust
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - toc.integrate
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true
