name: Install LuaJIT

on:
  workflow_call:
    inputs:
      version:
        description: 'LuaJIT Version (GitHub Release tag)'
        required: true
        default: 'v0.1.13'

jobs:
  install-luajit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up directories
        shell: bash
        run: |
          mkdir -p "$HOME/.local/bin"

      - name: Download LuaJIT binary (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          curl -L -o luajit "https://github.com/ShadowDara/LuaAPI-Rust/releases/download/${{ github.event.inputs.version }}/luajit-linux-x86_64"
          chmod +x luajit
          mv luajit "$HOME/.local/bin/luajit"

      - name: Download LuaJIT binary (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $url = "https://github.com/ShadowDara/LuaAPI-Rust/releases/download/${{ github.event.inputs.version }}/luajit-windows-x86_64.exe"
          $dest = "$env:USERPROFILE\.local\bin\luajit.exe"
          New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.local\bin"
          Invoke-WebRequest -Uri $url -OutFile $dest

      - name: Add to PATH (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Add to PATH (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: echo "$env:USERPROFILE\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify LuaJIT install
        shell: bash
        run: |
          luajit --version || echo "LuaJIT not found"
